language: python

python:
  - 3.8

before_install:
  - pip install poetry

install:
  - cd quart_backend
  - poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

script:
  - pytest
