language: python

python:
  - 3.6
  - 3.8

before_install:
  - pip install poetry

install:
  - poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

script:
  - pytest
